# Generated by Django 3.0.2 on 2020-01-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strhistory',
            name='nmbr_cnt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='strhistory',
            name='word_cnt',
            field=models.IntegerField(null=True),
        ),
    ]
