# Generated by Django 3.0.2 on 2020-01-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200105_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strhistory',
            name='number_count',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='strhistory',
            name='word_count',
            field=models.IntegerField(default=None),
        ),
    ]
